# -*- coding: utf-8 -*-
"""Copy of "A2_RNNs.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQmRxdRIE9N7HqLD-d7KLFp5oL9yffTZ

# Introduction to Deep Learning, Assignment 2, Task 2

# Introduction


The goal of this assignment is to learn how to use encoder-decoder recurrent neural networks (RNNs). Specifically we will be dealing with a sequence to sequence problem and try to build recurrent models that can learn the principles behind simple arithmetic operations (**integer addition, subtraction and multiplication.**).

<img src="https://i.ibb.co/5Ky5pbk/Screenshot-2023-11-10-at-07-51-21.png" alt="Screenshot-2023-11-10-at-07-51-21" border="0" width="500"></a>

In this assignment you will be working with three different kinds of models, based on input/output data modalities:
1. **Text-to-text**: given a text query containing two integers and an operand between them (+ or -) the model's output should be a sequence of integers that match the actual arithmetic result of this operation
2. **Image-to-text**: same as above, except the query is specified as a sequence of images containing individual digits and an operand.
3. **Text-to-image**: the query is specified in text format as in the text-to-text model, however the model's output should be a sequence of images corresponding to the correct result.


### Description
Let us suppose that we want to develop a neural network that learns how to add or subtract
two integers that are at most two digits long. For example, given input strings of 5 characters: ‘81+24’ or
’41-89’ that consist of 2 two-digit long integers and an operand between them, the network should return a
sequence of 3 characters: ‘105 ’ or ’-48 ’ that represent the result of their respective queries. Additionally,
we want to build a model that generalizes well - if the network can extract the underlying principles behind
the ’+’ and ’-’ operands and associated operations, it should not need too many training examples to generate
valid answers to unseen queries. To represent such queries we need 13 unique characters: 10 for digits (0-9),
2 for the ’+’ and ’-’ operands and one for whitespaces ’ ’ used as padding.
The example above describes a text-to-text sequence mapping scenario. However, we can also use different
modalities of data to represent our queries or answers. For that purpose, the MNIST handwritten digit
dataset is going to be used again, however in a slightly different format. The functions below will be used to create our datasets.

---

*To work on this notebook you should create a copy of it.*

When using the Lab Computers, download the Jupyter Notebook to one of the machines first.

If you want to use Google Colab, you should first copy this notebook and enable GPU runtime in 'Runtime -> Change runtime type -> Hardware acceleration -> GPU **OR** TPU'.

# Function definitions for creating the datasets

First we need to create our datasets that are going to be used for training our models.

In order to create image queries of simple arithmetic operations such as '15+13' or '42-10' we need to create images of '+' and '-' signs using ***open-cv*** library. We will use these operand signs together with the MNIST dataset to represent the digits.
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import cv2
import numpy as np
import tensorflow as tf
import random
from sklearn.model_selection import train_test_split

from tensorflow.keras.layers import Dense, RNN, LSTM, Flatten, TimeDistributed, LSTMCell
from tensorflow.keras.layers import (
    RepeatVector,
    Conv2D,
    SimpleRNN,
    GRU,
    Reshape,
    ConvLSTM2D,
    Conv2DTranspose,
    BatchNormalization,
    Dropout,
)
from tensorflow.keras import backend as K

from scipy.ndimage import rotate


# Create plus/minus operand signs
def generate_images(number_of_images=50, sign="-"):
    blank_images = np.zeros(
        [number_of_images, 28, 28]
    )  # Dimensionality matches the size of MNIST images (28x28)
    x = np.random.randint(12, 16, (number_of_images, 2))  # Randomized x coordinates
    y1 = np.random.randint(6, 10, number_of_images)  # Randomized y coordinates
    y2 = np.random.randint(18, 22, number_of_images)  # -||-

    for i in range(number_of_images):  # Generate n different images
        cv2.line(
            blank_images[i],
            (y1[i], x[i, 0]),
            (y2[i], x[i, 1]),
            (255, 0, 0),
            2,
            cv2.LINE_AA,
        )  # Draw lines with randomized coordinates
        if sign == "+":
            cv2.line(
                blank_images[i],
                (x[i, 0], y1[i]),
                (x[i, 1], y2[i]),
                (255, 0, 0),
                2,
                cv2.LINE_AA,
            )  # Draw lines with randomized coordinates

    return blank_images


def show_generated(images, n=5):
    plt.figure(figsize=(2, 2))
    for i in range(n**2):
        plt.subplot(n, n, i + 1)
        plt.axis("off")
        plt.imshow(images[i])
    plt.show()


show_generated(generate_images())
show_generated(generate_images(sign="+"))


def create_data(highest_integer, num_addends=2, operands=["+", "-"]):
    """
    Creates the following data for all pairs of integers up to [1:highest integer][+/-][1:highest_integer]:

    @return:
    X_text: '51+21' -> text query of an arithmetic operation (5)
    X_img : Stack of MNIST images corresponding to the query (5 x 28 x 28) -> sequence of 5 images of size 28x28
    y_text: '72' -> answer of the arithmetic text query
    y_img :  Stack of MNIST images corresponding to the answer (3 x 28 x 28)

    Images for digits are picked randomly from the whole MNIST dataset.
    """

    num_indices = [np.where(MNIST_labels == x) for x in range(10)]
    num_data = [MNIST_data[inds] for inds in num_indices]
    image_mapping = dict(zip(unique_characters[:10], num_data))
    image_mapping["-"] = generate_images()
    image_mapping["+"] = generate_images(sign="+")
    image_mapping["*"] = generate_images(sign="*")
    image_mapping[" "] = np.zeros([1, 28, 28])

    X_text, X_img, y_text, y_img = [], [], [], []

    for i in range(highest_integer + 1):  # First addend
        for j in range(highest_integer + 1):  # Second addend
            for sign in operands:  # Create all possible combinations of operands
                query_string = to_padded_chars(
                    str(i) + sign + str(j), max_len=max_query_length, pad_right=True
                )
                query_image = []
                for n, char in enumerate(query_string):
                    image_set = image_mapping[char]
                    index = np.random.randint(0, len(image_set), 1)
                    query_image.append(image_set[index].squeeze())

                result = eval(query_string)
                result_string = to_padded_chars(
                    result, max_len=max_answer_length, pad_right=True
                )
                result_image = []
                for n, char in enumerate(result_string):
                    image_set = image_mapping[char]
                    index = np.random.randint(0, len(image_set), 1)
                    result_image.append(image_set[index].squeeze())

                X_text.append(query_string)
                X_img.append(np.stack(query_image))
                y_text.append(result_string)
                y_img.append(np.stack(result_image))

    return (
        np.stack(X_text),
        np.stack(X_img) / 255.0,
        np.stack(y_text),
        np.stack(y_img) / 255.0,
    )


def to_padded_chars(integer, max_len=3, pad_right=False):
    """
    Returns a string of len()=max_len, containing the integer padded with ' ' on either right or left side
    """
    length = len(str(integer))
    padding = (max_len - length) * " "
    if pad_right:
        return str(integer) + padding
    else:
        return padding + str(integer)


"""# Creating our data

The dataset consists of 20000 samples that (additions and subtractions between all 2-digit integers) and they have two kinds of inputs and label modalities:

  **X_text**: strings containing queries of length 5: ['  1+1  ', '11-18', ...]

  **X_image**: a stack of images representing a single query, dimensions: [5, 28, 28]

  **y_text**: strings containing answers of length 3: ['  2', '156']

  **y_image**: a stack of images that represents the answer to a query, dimensions: [3, 28, 28]
"""

# Illustrate the generated query/answer pairs

unique_characters = "0123456789+- "  # All unique characters that are used in the queries (13 in total: digits 0-9, 2 operands [+, -], and a space character ' '.)
highest_integer = 99  # Highest value of integers contained in the queries

max_int_length = len(str(highest_integer))  # Maximum number of characters in an integer
max_query_length = (
    max_int_length * 2 + 1
)  # Maximum length of the query string (consists of two integers and an operand [e.g. '22+10'])
max_answer_length = 3  # Maximum length of the answer string (the longest resulting query string is ' 1-99'='-98')

# Create the data (might take around a minute)
(MNIST_data, MNIST_labels), _ = tf.keras.datasets.mnist.load_data()
X_text, X_img, y_text, y_img = create_data(highest_integer)
print(X_text.shape, X_img.shape, y_text.shape, y_img.shape)


## Display the samples that were created
def display_sample(n):
    labels = ["X_img:", "y_img:"]
    for i, data in enumerate([X_img, y_img]):
        plt.subplot(1, 2, i + 1)
        # plt.set_figheight(15)
        plt.axis("off")
        plt.title(labels[i])
        plt.imshow(np.hstack(data[n]), cmap="gray")
    print("=" * 50, f'\nQuery #{n}\n\nX_text: "{X_text[n]}" = y_text: "{y_text[n]}"')
    plt.show()


for _ in range(10):
    display_sample(np.random.randint(0, 10000, 1)[0])

"""## Helper functions

The functions below will help with input/output of the data.
"""

# One-hot encoding/decoding the text queries/answers so that they can be processed using RNNs
# You should use these functions to convert your strings and read out the output of your networks


def encode_labels(labels, max_len=3):
    n = len(labels)
    length = len(labels[0])
    char_map = dict(zip(unique_characters, range(len(unique_characters))))
    one_hot = np.zeros([n, length, len(unique_characters)])
    for i, label in enumerate(labels):
        m = np.zeros([length, len(unique_characters)])
        for j, char in enumerate(label):
            m[j, char_map[char]] = 1
        one_hot[i] = m

    return one_hot


def decode_labels(labels):
    pred = np.argmax(labels, axis=2)
    predicted = ["".join([unique_characters[i] for i in j]) for j in pred]

    return predicted


X_text_onehot = encode_labels(X_text)
y_text_onehot = encode_labels(y_text)

print(X_text_onehot.shape, y_text_onehot.shape)

"""---
---

## I. Text-to-text RNN model

The following code showcases how Recurrent Neural Networks (RNNs) are built using Keras. Several new layers are going to be used:

1. LSTM
2. TimeDistributed
3. RepeatVector

The code cell below explains each of these new components.

<img src="https://i.ibb.co/NY7FFTc/Screenshot-2023-11-10-at-09-27-25.png" alt="Screenshot-2023-11-10-at-09-27-25" border="0" width="500"></a>

"""


def build_text2text_model():

    # We start by initializing a sequential model
    text2text = tf.keras.Sequential()

    # "Encode" the input sequence using an RNN, producing an output of size 256.
    # In this case the size of our input vectors is [5, 13] as we have queries of length 5 and 13 unique characters. Each of these 5 elements in the query will be fed to the network one by one,
    # as shown in the image above (except with 5 elements).
    # Hint: In other applications, where your input sequences have a variable length (e.g. sentences), you would use input_shape=(None, unique_characters).
    text2text.add(LSTM(256, input_shape=(None, len(unique_characters))))

    # As the decoder RNN's input, repeatedly provide with the last output of RNN for each time step. Repeat 3 times as that's the maximum length of the output (e.g. '  1-99' = '-98')
    # when using 2-digit integers in queries. In other words, the RNN will always produce 3 characters as its output.
    text2text.add(RepeatVector(max_answer_length))

    # By setting return_sequences to True, return not only the last output but all the outputs so far in the form of (num_samples, timesteps, output_dim). This is necessary as TimeDistributed in the below expects
    # the first dimension to be the timesteps.
    text2text.add(LSTM(256, return_sequences=True))

    # Apply a dense layer to the every temporal slice of an input. For each of step of the output sequence, decide which character should be chosen.
    text2text.add(TimeDistributed(Dense(len(unique_characters), activation="softmax")))

    # Next we compile the model using categorical crossentropy as our loss function.
    text2text.compile(
        loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"]
    )
    text2text.summary()

    return text2text


## Your code (look at the assignment description for your tasks for text-to-text model):
## Your first task is to fit the text2text model using X_text and y_text)


# ============================================================
# Summary of results for different train/test split ratios
# ============================================================

# Training set ratio: 50.0%
#   Training accuracy: 0.7193
#   Test accuracy: 0.6927
#   Exact match accuracy: 0.1943

# Training set ratio: 25.0%
#   Training accuracy: 0.6636
#   Test accuracy: 0.6317
#   Exact match accuracy: 0.0786

# Training set ratio: 10.0%
#   Training accuracy: 0.5672
#   Test accuracy: 0.5386
#   Exact match accuracy: 0.0483


def train_and_evaluate_model(
    train_splits, model_builder, X_data, y_data, model_name=""
):
    """
    Generic function to train and evaluate models with different train/test splits.

    Args:
        train_splits: List of training set ratios (e.g., [0.5, 0.25, 0.1])
        model_builder: Function that returns a compiled model
        X_data: Input data (X_text_onehot or X_img)
        y_data: Output data (y_text_onehot)
        model_name: Optional name for the model (for display purposes)
    """
    results = {}
    for train_ratio in train_splits:
        print(
            f"Training set ratio: {train_ratio*100}%, Test set ratio: {(1-train_ratio)*100}%"
        )

        # Split data
        X_train, X_test, y_train, y_test = train_test_split(
            X_data,
            y_data,
            train_size=train_ratio,
            test_size=1 - train_ratio,
            random_state=66,
        )

        print(
            f"Training set size: {X_train.shape[0]}, Test set size: {X_test.shape[0]}"
        )

        # Build a new model for this split
        model = model_builder()

        history = model.fit(
            X_train, y_train, batch_size=32, epochs=20, validation_split=0.2
        )

        # Evaluate model
        train_loss, train_acc = model.evaluate(X_train, y_train)
        test_loss, test_acc = model.evaluate(X_test, y_test)

        # Make predictions
        y_pred = model.predict(X_test)
        y_pred_text = decode_labels(y_pred)
        y_test_text = decode_labels(y_test)

        # Calculate exact match accuracy (entire sequence must be correct)
        match_count = 0
        for i in range(len(y_test_text)):
            if y_test_text[i] == y_pred_text[i]:
                match_count += 1
        exact_match = match_count / len(y_test_text)

        print(f"Exact match accuracy: {exact_match:.4f}")

        # Plot loss
        plt.plot(history.history["loss"], label="Training loss")
        plt.plot(history.history["val_loss"], label="Validation loss")
        title = (
            f"{model_name} Model Loss (Training set ratio: {train_ratio*100}%)"
            if model_name
            else f"Model Loss (Training set ratio: {train_ratio*100}%)"
        )
        plt.title(title)
        plt.xlabel("Epoch")
        plt.ylabel("Loss")
        plt.legend()
        plt.grid(True)
        plt.show()

        # Plot accuracy
        plt.plot(history.history["accuracy"], label="Training accuracy")
        plt.plot(history.history["val_accuracy"], label="Validation accuracy")
        title = (
            f"{model_name} Model Accuracy (Training set ratio: {train_ratio*100}%)"
            if model_name
            else f"Model Accuracy (Training set ratio: {train_ratio*100}%)"
        )
        plt.title(title)
        plt.xlabel("Epoch")
        plt.ylabel("Accuracy")
        plt.legend()
        plt.grid(True)
        plt.show()

        print(f"\nTraining set ratio: {train_ratio*100}%")
        print(f"  Training accuracy: {train_acc:.4f}")
        print(f"  Test accuracy: {test_acc:.4f}")
        print(f"  Exact match accuracy: {exact_match:.4f}")

        results[train_ratio] = {
            "train_acc": train_acc,
            "test_acc": test_acc,
            "exact_match": exact_match,
        }

    return results


# Split dataset into training and test sets
# Try different split ratios: 50-50, 25-75, 10-90
train_splits = [0.5, 0.25, 0.1]

train_and_evaluate_model(
    train_splits, build_text2text_model, X_text_onehot, y_text_onehot, "Text-to-Text"
)
"""
---
---

## II. Image to text RNN Model

Hint: There are two ways of building the encoder for such a model - again by using the regular LSTM cells (with flattened images as input vectors) or recurrect convolutional layers [ConvLSTM2D](https://keras.io/api/layers/recurrent_layers/conv_lstm2d/).

The goal here is to use **X_img** as inputs and **y_text** as outputs."""


# Method 1: Using LSTM with flattened images
def build_img2text_model_lstm():
    """
    Build an image-to-text model using LSTM encoder with flattened images.
    Input: X_img shape (n_samples, 5, 28, 28) - sequence of 5 images
    Output: y_text_onehot shape (n_samples, 3, 13) - sequence of 3 characters
    """
    model = tf.keras.Sequential()

    # Flatten each 28x28 image to a 784-dimensional vector
    # Input shape: (5, 28, 28) -> (5, 784)
    model.add(TimeDistributed(Flatten(), input_shape=(max_query_length, 28, 28)))

    # Encoder: LSTM to process the sequence of flattened images
    model.add(LSTM(256))

    # Repeat the encoded representation for decoder
    model.add(RepeatVector(max_answer_length))

    # Decoder: LSTM to generate output sequence
    model.add(LSTM(256, return_sequences=True))

    # Output layer: Dense layer for each time step to predict character
    model.add(TimeDistributed(Dense(len(unique_characters), activation="softmax")))

    model.compile(
        loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"]
    )
    model.summary()

    return model


# Method 2: Using ConvLSTM2D
def build_img2text_model_convlstm():
    """
    Build an image-to-text model using ConvLSTM2D encoder.
    Input: X_img shape (n_samples, 5, 28, 28) - sequence of 5 images
    Output: y_text_onehot shape (n_samples, 3, 13) - sequence of 3 characters
    """
    model = tf.keras.Sequential()

    # Reshape input to add channel dimension: (5, 28, 28) -> (5, 28, 28, 1)
    model.add(
        Reshape((max_query_length, 28, 28, 1), input_shape=(max_query_length, 28, 28))
    )

    # Encoder: ConvLSTM2D to process sequence of images
    # ConvLSTM2D processes spatial-temporal data
    model.add(
        ConvLSTM2D(
            filters=32,
            kernel_size=(3, 3),
            padding="same",
            return_sequences=False,  # Only return final output
        )
    )

    # Flatten the output from ConvLSTM2D
    model.add(Flatten())

    # Dense layer to reduce dimensions before decoder
    model.add(Dense(256, activation="relu"))

    # Repeat for decoder
    model.add(RepeatVector(max_answer_length))

    # Decoder: LSTM to generate output sequence
    model.add(LSTM(256, return_sequences=True))

    # Output layer: Dense layer for each time step
    model.add(TimeDistributed(Dense(len(unique_characters), activation="softmax")))

    model.compile(
        loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"]
    )
    model.summary()

    return model


# Train and evaluate both models
print("=" * 60)
print("Image-to-Text RNN Model Training")
print("=" * 60)

# Method 1: LSTM with flattened images
print("\n" + "=" * 60)
print("Method 1: LSTM with Flattened Images")
print("=" * 60)

results_lstm = train_and_evaluate_model(
    train_splits, build_img2text_model_lstm, X_img, y_text_onehot, "Image-to-Text LSTM"
)

# Method 2: ConvLSTM2D
print("\n" + "=" * 60)
print("Method 2: ConvLSTM2D")
print("=" * 60)

results_convlstm = train_and_evaluate_model(
    train_splits,
    build_img2text_model_convlstm,
    X_img,
    y_text_onehot,
    "Image-to-Text ConvLSTM2D",
)

# Compare results
print("\n" + "=" * 60)
print("Comparison: Image-to-Text Models")
print("=" * 60)
for train_ratio in train_splits:
    print(f"\nTraining set ratio: {train_ratio*100}%")
    print(f"  LSTM Model:")
    print(f"    Test accuracy: {results_lstm[train_ratio]['test_acc']:.4f}")
    print(f"    Exact match: {results_lstm[train_ratio]['exact_match']:.4f}")
    print(f"  ConvLSTM2D Model:")
    print(f"    Test accuracy: {results_convlstm[train_ratio]['test_acc']:.4f}")
    print(f"    Exact match: {results_convlstm[train_ratio]['exact_match']:.4f}")

"""---
---

## III. Text to image RNN Model

Hint: to make this model work really well you could use deconvolutional layers in your decoder (you might need to look up ***Conv2DTranspose*** layer). However, regular vector-based decoder will work as well.

The goal here is to use **X_text** as inputs and **y_img** as outputs.
"""


# Using Conv2DTranspose decoder
def build_text2img_model_convtranspose():
    """
    Build a text-to-image model using Conv2DTranspose decoder.
    Input: X_text_onehot shape (n_samples, 5, 13) - sequence of 5 characters
    Output: y_img shape (n_samples, 3, 28, 28) - sequence of 3 images
    """
    model = tf.keras.Sequential()

    # Encoder: LSTM to process the text sequence
    model.add(LSTM(256, input_shape=(None, len(unique_characters))))

    # Repeat the encoded representation for decoder
    model.add(RepeatVector(max_answer_length))

    # Decoder: LSTM to generate output sequence
    model.add(LSTM(256, return_sequences=True))

    # Dense layer to generate feature maps
    # We'll reshape to (timesteps, 7, 7, 64) to use Conv2DTranspose
    model.add(TimeDistributed(Dense(7 * 7 * 64, activation="relu")))
    model.add(TimeDistributed(Reshape((7, 7, 64))))

    # Use Conv2DTranspose to upsample to 28x28
    # 7x7 -> 14x14 -> 28x28
    model.add(
        TimeDistributed(
            Conv2DTranspose(
                32, (3, 3), strides=(2, 2), padding="same", activation="relu"
            )
        )
    )
    model.add(
        TimeDistributed(
            Conv2DTranspose(
                1, (3, 3), strides=(2, 2), padding="same", activation="sigmoid"
            )
        )
    )

    # Remove the channel dimension: (timesteps, 28, 28, 1) -> (timesteps, 28, 28)
    model.add(TimeDistributed(Reshape((28, 28))))

    model.compile(loss="mse", optimizer="adam", metrics=["mse"])
    model.summary()

    return model


# Special training and evaluation function for image output
def train_and_evaluate_img_model(
    train_splits, model_builder, X_data, y_data, model_name=""
):
    """
    Train and evaluate models with image outputs.

    Args:
        train_splits: List of training set ratios
        model_builder: Function that returns a compiled model
        X_data: Input data (X_text_onehot)
        y_data: Output data (y_img)
        model_name: Optional name for the model
    """
    results = {}
    for train_ratio in train_splits:
        print(
            f"Training set ratio: {train_ratio*100}%, Test set ratio: {(1-train_ratio)*100}%"
        )

        # Split data
        X_train, X_test, y_train, y_test = train_test_split(
            X_data,
            y_data,
            train_size=train_ratio,
            test_size=1 - train_ratio,
            random_state=66,
        )

        print(
            f"Training set size: {X_train.shape[0]}, Test set size: {X_test.shape[0]}"
        )

        # Build a new model for this split
        model = model_builder()

        history = model.fit(
            X_train,
            y_train,
            batch_size=32,
            epochs=20,
            validation_split=0.2,
        )

        # Evaluate model
        train_loss, train_mse = model.evaluate(X_train, y_train, verbose=0)
        test_loss, test_mse = model.evaluate(X_test, y_test, verbose=0)

        print(f"Training MSE: {train_mse:.6f}")
        print(f"Test MSE: {test_mse:.6f}")

        # Make predictions
        y_pred = model.predict(X_test, verbose=0)

        # Calculate pixel-wise accuracy (threshold at 0.5)
        y_pred_binary = (y_pred > 0.5).astype(float)
        y_test_binary = (y_test > 0.5).astype(float)
        pixel_accuracy = np.mean(y_pred_binary == y_test_binary)
        print(f"Pixel accuracy: {pixel_accuracy:.4f}")

        # Plot loss
        plt.plot(history.history["loss"], label="Training loss")
        plt.plot(history.history["val_loss"], label="Validation loss")
        title = (
            f"{model_name} Model Loss (Training set ratio: {train_ratio*100}%)"
            if model_name
            else f"Model Loss (Training set ratio: {train_ratio*100}%)"
        )
        plt.title(title)
        plt.xlabel("Epoch")
        plt.ylabel("MSE Loss")
        plt.legend()
        plt.grid(True)
        plt.show()

        print(f"\nTraining set ratio: {train_ratio*100}%")
        print(f"  Training MSE: {train_mse:.6f}")
        print(f"  Test MSE: {test_mse:.6f}")
        print(f"  Pixel accuracy: {pixel_accuracy:.4f}")

        results[train_ratio] = {
            "train_mse": train_mse,
            "test_mse": test_mse,
            "pixel_accuracy": pixel_accuracy,
            "y_pred": y_pred,
            "y_test": y_test,
        }

    return results


# Train and evaluate the model
print("=" * 60)
print("Text-to-Image RNN Model Training")
print("=" * 60)

results_convtranspose = train_and_evaluate_img_model(
    train_splits,
    build_text2img_model_convtranspose,
    X_text_onehot,
    y_img,
    "Text-to-Image Conv2DTranspose",
)

# Show detailed examples for each training ratio
print("\n" + "=" * 60)
print("Detailed Examples: Text-to-Image Predictions")
print("=" * 60)

# Show detailed examples for each training ratio
for train_ratio in train_splits:
    print("\n" + "=" * 60)
    print(f"Training Ratio: {train_ratio*100}%")
    print("=" * 60)

    # Get the corresponding test set text using the same split
    _, X_text_test, _, _ = train_test_split(
        X_text,
        y_text,
        train_size=train_ratio,
        test_size=1 - train_ratio,
        random_state=66,
    )

    # Get predictions and test data for this ratio
    y_pred_convtranspose = results_convtranspose[train_ratio]["y_pred"]
    y_test_vis = results_convtranspose[train_ratio]["y_test"]

    print(
        f"\nShowing detailed examples (first 5) for training ratio {train_ratio*100}%:"
    )

    for i in range(min(5, len(y_test_vis))):
        print(f"\nExample {i+1}:")
        print(f"  Input text: '{X_text_test[i]}'")

        fig, axes = plt.subplots(1, 2, figsize=(10, 5))

        # True images
        axes[0].imshow(np.hstack(y_test_vis[i]), cmap="gray")
        axes[0].set_title("True Images", fontsize=12, fontweight="bold")
        axes[0].axis("off")

        # Generated predictions
        axes[1].imshow(np.hstack(y_pred_convtranspose[i]), cmap="gray")
        axes[1].set_title("Generated Images", fontsize=12)
        axes[1].axis("off")

        plt.tight_layout()
        plt.show()

# Print summary statistics
print("\n" + "=" * 60)
print("Model Performance Summary")
print("=" * 60)
for train_ratio in train_splits:
    print(f"\nTraining set ratio: {train_ratio*100}%")
    print(f"  Test MSE: {results_convtranspose[train_ratio]['test_mse']:.6f}")
    print(
        f"  Pixel accuracy: {results_convtranspose[train_ratio]['pixel_accuracy']:.4f}"
    )

"""
---
---

## IV. Text-to-Text Model with Additional LSTM Layers

Try adding additional LSTM layers to your encoder networks and see how the performance of your
models changes. Try to explain these performance differences in the context of the mistakes that
your network was making before. Tip: you should add a flag "return_sequences=True" to the first
recurrent layer of your network.
"""


# Improved Text-to-Text model with additional LSTM layers in encoder
def build_text2text_model_improved():
    """
    Build an improved text-to-text model with additional LSTM layers in the encoder.
    The first LSTM layer uses return_sequences=True to pass sequences to the next layer.
    This allows the model to capture more complex patterns in the input sequence.
    """
    model = tf.keras.Sequential()

    # First LSTM layer with return_sequences=True to pass sequences to next layer
    # This allows stacking multiple LSTM layers
    model.add(
        LSTM(256, return_sequences=True, input_shape=(None, len(unique_characters)))
    )

    # Second LSTM layer in encoder - processes the sequences from first layer
    # This can capture higher-level patterns and dependencies
    model.add(LSTM(256))  # Final encoder output

    # Repeat the encoded representation for decoder
    model.add(RepeatVector(max_answer_length))

    # Decoder: LSTM to generate output sequence
    model.add(LSTM(256, return_sequences=True))

    # Output layer: Dense layer for each time step
    model.add(TimeDistributed(Dense(len(unique_characters), activation="softmax")))

    # Compile the model
    model.compile(
        loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"]
    )
    model.summary()

    return model


# Train and compare both models
print("=" * 60)
print("Text-to-Text Model Comparison")
print("=" * 60)
print("\n1. Original Model (Single LSTM layer in encoder)")
print("-" * 60)

# Train original model
results_original = train_and_evaluate_model(
    train_splits,
    build_text2text_model,
    X_text_onehot,
    y_text_onehot,
    "Text-to-Text Original",
)

print("\n" + "=" * 60)
print("2. Improved Model (Multiple LSTM layers in encoder)")
print("-" * 60)

# Train improved model
results_improved = train_and_evaluate_model(
    train_splits,
    build_text2text_model_improved,
    X_text_onehot,
    y_text_onehot,
    "Text-to-Text Improved",
)

# Compare results
print("\n" + "=" * 60)
print("Performance Comparison: Original vs Improved Model")
print("=" * 60)

comparison_data = []
for train_ratio in train_splits:
    orig = results_original[train_ratio]
    impr = results_improved[train_ratio]

    print(f"\nTraining set ratio: {train_ratio*100}%")
    print(f"{'Metric':<25} {'Original':<15} {'Improved':<15} {'Difference':<15}")
    print("-" * 70)

    # Training accuracy
    train_acc_diff = impr["train_acc"] - orig["train_acc"]
    print(
        f"{'Training Accuracy':<25} {orig['train_acc']:<15.4f} {impr['train_acc']:<15.4f} {train_acc_diff:+.4f}"
    )

    # Test accuracy
    test_acc_diff = impr["test_acc"] - orig["test_acc"]
    print(
        f"{'Test Accuracy':<25} {orig['test_acc']:<15.4f} {impr['test_acc']:<15.4f} {test_acc_diff:+.4f}"
    )

    # Exact match accuracy
    exact_match_diff = impr["exact_match"] - orig["exact_match"]
    print(
        f"{'Exact Match Accuracy':<25} {orig['exact_match']:<15.4f} {impr['exact_match']:<15.4f} {exact_match_diff:+.4f}"
    )

    comparison_data.append(
        {
            "train_ratio": train_ratio,
            "original_train_acc": orig["train_acc"],
            "improved_train_acc": impr["train_acc"],
            "original_test_acc": orig["test_acc"],
            "improved_test_acc": impr["test_acc"],
            "original_exact_match": orig["exact_match"],
            "improved_exact_match": impr["exact_match"],
        }
    )

# Summary analysis
print("\n" + "=" * 60)
print("Summary Analysis")
print("=" * 60)
print("\nKey Observations:")
print("1. Encoder Architecture:")
print("   - Original: Single LSTM layer (256 units)")
print("   - Improved: Two stacked LSTM layers (256 units each)")
print("   - The first LSTM uses return_sequences=True to enable layer stacking")
print("\n2. Expected Benefits:")
print("   - Better capture of long-range dependencies in input sequence")
print("   - More complex pattern recognition in arithmetic operations")
print("   - Improved handling of sequential relationships")
print("\n3. Potential Trade-offs:")
print("   - More parameters = longer training time")
print("   - Risk of overfitting with small datasets")
print("   - May require more training data to see benefits")

# Visual comparison
print("\n" + "=" * 60)
print("Visual Comparison: Test Accuracy")
print("=" * 60)

train_ratios = [r * 100 for r in train_splits]
original_test_accs = [results_original[r]["test_acc"] for r in train_splits]
improved_test_accs = [results_improved[r]["test_acc"] for r in train_splits]

plt.figure(figsize=(10, 6))
plt.plot(
    train_ratios,
    original_test_accs,
    "o-",
    label="Original Model",
    linewidth=2,
    markersize=8,
)
plt.plot(
    train_ratios,
    improved_test_accs,
    "s-",
    label="Improved Model (Multi-LSTM)",
    linewidth=2,
    markersize=8,
)
plt.xlabel("Training Set Ratio (%)", fontsize=12)
plt.ylabel("Test Accuracy", fontsize=12)
plt.title(
    "Text-to-Text Model Comparison: Test Accuracy", fontsize=14, fontweight="bold"
)
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.xticks(train_ratios)
plt.tight_layout()
plt.show()

print("\n" + "=" * 60)
print("Visual Comparison: Exact Match Accuracy")
print("=" * 60)

original_exact = [results_original[r]["exact_match"] for r in train_splits]
improved_exact = [results_improved[r]["exact_match"] for r in train_splits]

plt.figure(figsize=(10, 6))
plt.plot(
    train_ratios,
    original_exact,
    "o-",
    label="Original Model",
    linewidth=2,
    markersize=8,
)
plt.plot(
    train_ratios,
    improved_exact,
    "s-",
    label="Improved Model (Multi-LSTM)",
    linewidth=2,
    markersize=8,
)
plt.xlabel("Training Set Ratio (%)", fontsize=12)
plt.ylabel("Exact Match Accuracy", fontsize=12)
plt.title(
    "Text-to-Text Model Comparison: Exact Match Accuracy",
    fontsize=14,
    fontweight="bold",
)
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.xticks(train_ratios)
plt.tight_layout()
plt.show()

print("\n" + "=" * 60)
print("Analysis Complete")
print("=" * 60)
